import { Check, Copy, Loader2, LogOut } from "lucide-react";
import { CiGift } from "react-icons/ci";
import {
  FaArrowRight,
  FaGithub,
  FaGoogle,
  FaLinkedinIn,
  FaProductHunt,
} from "react-icons/fa";
import { FaCheck, FaXTwitter } from "react-icons/fa6";
import { LuLoader2, LuMonitor, LuMoon, LuSun } from "react-icons/lu";
import {
  MdAdd,
  MdArrowBack,
  MdArrowLeft,
  MdArrowUpward,
  MdAutoAwesome,
  MdBarChart,
  MdChangeHistory,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdCreateNewFolder,
  MdDescription,
  MdDriveFileMove,
  MdEditCalendar,
  MdErrorOutline,
  MdExpandLess,
  MdExpandMore,
  MdFence,
  MdFileUpload,
  MdFolder,
  MdFolderSpecial,
  MdFolderZip,
  MdInventory2,
  MdIosShare,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdMoreHoriz,
  MdOutlineArrowDownward,
  MdOutlineArrowForward,
  MdOutlineAutoAwesome,
  MdOutlineBackspace,
  MdOutlineBrokenImage,
  MdOutlineCancel,
  MdOutlineCategory,
  MdOutlineChatBubbleOutline,
  MdOutlineContentCopy,
  MdOutlineDashboardCustomize,
  MdOutlineDelete,
  MdOutlineDescription,
  MdOutlineEmail,
  MdOutlineExitToApp,
  MdOutlineFace,
  MdOutlineFileDownload,
  MdOutlineForwardToInbox,
  MdOutlineHandyman,
  MdOutlineHourglassTop,
  MdOutlineInbox,
  MdOutlineInsertPhoto,
  MdOutlineIntegrationInstructions,
  MdOutlineInventory2,
  MdOutlineListAlt,
  MdOutlineMoreVert,
  MdOutlineMoveToInbox,
  MdOutlineNotificationsNone,
  MdOutlineOpenInFull,
  MdOutlinePalette,
  MdOutlinePause,
  MdOutlinePlayArrow,
  MdOutlineQuestionAnswer,
  MdOutlineSettings,
  MdOutlineSubject,
  MdOutlineTask,
  MdOutlineTimer,
  MdOutlineTune,
  MdOutlineVisibility,
  MdPause,
  MdPauseCircle,
  MdPeople,
  MdPerson,
  MdPictureAsPdf,
  MdPlayArrow,
  MdPlayCircle,
  MdRefresh,
  MdRemove,
  MdReplay,
  MdRuleFolder,
  MdSearch,
  MdSecurity,
  MdSignalCellularAlt,
  MdSort,
  MdSubdirectoryArrowLeft,
  MdTopic,
  MdTrendingDown,
  MdTrendingUp,
} from "react-icons/md";
import { PiDiscordLogo, PiSpeedometer } from "react-icons/pi";
import { TbSlash } from "react-icons/tb";
import { VscLayoutSidebarLeft, VscLayoutSidebarLeftOff } from "react-icons/vsc";

export const Icons = {
  // ℹ️ TODO: Update your company Logo here
  Logo: ({ className }: { className?: string }) => (
    <svg
      width={32}
      height={32}
      viewBox="0 0 424 424"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      <path
        d="M372.347 269.799L221.561 341.062C216.281 343.557 210.167 343.578 204.871 341.119L51.4158 269.855C36.2356 262.805 36.2356 241.224 51.4158 234.175L204.871 162.911C210.167 160.452 216.281 160.472 221.56 162.967L372.347 234.231C387.367 241.33 387.367 262.7 372.347 269.799Z"
        fill="white"
        stroke="black"
        strokeWidth="17.8818"
        strokeLinejoin="round"
      />
      <path
        d="M372.347 230.459L221.561 301.722C216.281 304.217 210.167 304.238 204.871 301.779L51.4158 230.515C36.2356 223.465 36.2356 201.884 51.4158 194.835L204.871 123.571C210.167 121.112 216.281 121.132 221.56 123.627L372.347 194.891C387.367 201.99 387.367 223.36 372.347 230.459Z"
        fill="white"
        stroke="black"
        strokeWidth="17.8818"
        strokeLinejoin="round"
      />
      <path
        d="M372.834 188.769L222.048 260.033C216.769 262.528 210.654 262.548 205.358 260.089L51.9033 188.825C36.7232 181.776 36.7232 160.195 51.9033 153.145L205.358 81.8814C210.654 79.4221 216.769 79.4427 222.048 81.9377L372.834 153.201C387.854 160.3 387.854 181.67 372.834 188.769Z"
        fill="white"
        stroke="black"
        strokeWidth="17.8818"
        strokeLinejoin="round"
      />
    </svg>
  ),
  X: FaXTwitter,
  Discord: PiDiscordLogo,
  Github: FaGithub,
  Linkedin: FaLinkedinIn,
  ProductHunt: FaProductHunt,
  Google: FaGoogle,
  // Icons
  Slash: TbSlash,
  Moon: LuMoon,
  Sun: LuSun,
  Monitor: LuMonitor,
  Check: FaCheck,
  Speedometer: PiSpeedometer,
  Loader: LuLoader2,
  SidebarClosed: VscLayoutSidebarLeftOff,
  SidebarOpen: VscLayoutSidebarLeft,
  Gift: CiGift,
  Overview: MdBarChart,
  Apps: MdOutlineIntegrationInstructions,
  Transactions: MdOutlineListAlt,
  Invoice: MdOutlineDescription,
  Files: MdOutlineInventory2,
  Settings: MdOutlineSettings,
  Inbox2: MdOutlineInbox,
  Close: MdClose,
  Remove: MdRemove,
  Fence: MdFence,
  Refresh: MdRefresh,
  Inventory2: MdInventory2,
  Person: MdPerson,
  Peolple: MdPeople,
  Notifications: MdOutlineNotificationsNone,
  ChevronDown: MdExpandMore,
  ChevronUp: MdExpandLess,
  TrendingUp: MdTrendingUp,
  TrendingDown: MdTrendingDown,
  Category: MdOutlineCategory,
  Visibility: MdOutlineVisibility,
  Face: MdOutlineFace,
  MoreHoriz: MdMoreHoriz,
  Pdf: MdPictureAsPdf,
  DriveFileMove: MdDriveFileMove,
  Enter: MdSubdirectoryArrowLeft,
  FolderSpecial: MdFolderSpecial,
  Topic: MdTopic,
  BrokenImage: MdOutlineBrokenImage,
  Description: MdDescription,
  FolderZip: MdFolderZip,
  ChevronRight: MdChevronRight,
  ChevronLeft: MdChevronLeft,
  ArrowLeft: MdArrowLeft,
  ArrowRight: FaArrowRight,
  ArrowDown: MdOutlineArrowDownward,
  ArrowUp: MdArrowUpward,
  ArrowBack: MdArrowBack,
  KeyboardArrowDown: MdKeyboardArrowDown,
  KeyboardArrowUp: MdKeyboardArrowUp,
  KeyboardArrowLeft: MdKeyboardArrowLeft,
  KeyboardArrowRight: MdKeyboardArrowRight,
  ArrowForward: MdOutlineArrowForward,
  Folder: MdFolder,
  FileUpload: MdFileUpload,
  Search: MdSearch,
  CreateNewFolder: MdCreateNewFolder,
  Error: MdErrorOutline,
  OpenInFull: MdOutlineOpenInFull,
  FileDownload: MdOutlineFileDownload,
  Image: MdOutlineInsertPhoto,
  Security: MdSecurity,
  AI: MdAutoAwesome,
  AIOutline: MdOutlineAutoAwesome,
  Tracker: MdOutlineTimer,
  WorkInProgress: MdOutlineHandyman,
  Add: MdAdd,
  DashboardCustomize: MdOutlineDashboardCustomize,
  Copy: MdOutlineContentCopy,
  InboxEmpty: MdOutlineMoveToInbox,
  Share: MdIosShare,
  Cancel: MdOutlineCancel,
  Pending: MdOutlineHourglassTop,
  Play: MdPlayArrow,
  PlayOutline: MdOutlinePlayArrow,
  Pause: MdPause,
  PauseOutline: MdOutlinePause,
  PlayCircle: MdPlayCircle,
  PauseCircle: MdPauseCircle,
  MoreVertical: MdOutlineMoreVert,
  ExitToApp: MdOutlineExitToApp,
  Match: MdOutlineTask,
  Email: MdOutlineEmail,
  QuestionAnswer: MdOutlineQuestionAnswer,
  Click: MdSignalCellularAlt,
  Tune: MdOutlineTune,
  Change: MdChangeHistory,
  Forwarded: MdOutlineForwardToInbox,
  Delete: MdOutlineDelete,
  FolderImports: MdRuleFolder,
  FolderTransactions: MdTopic,
  Calendar: MdEditCalendar,
  Reply: MdReplay,
  Sort: MdSort,
  Backspace: MdOutlineBackspace,
  Palette: MdOutlinePalette,
  Subject: MdOutlineSubject,
  ChatBubble: MdOutlineChatBubbleOutline,
  SignOut: LogOut,
};
